using System.Globalization;
using System.Text.Json;
using CudaSpirit.Core.Models;
using CudaSpirit.Core.Services.Data;

namespace CudaSpirit.Core.Services.Knowledge;

public sealed class LocalImportReport
{
    public int FilesScanned { get; init; }
    public int FilesImported { get; init; }
    public int FilesSkipped { get; init; }
    public int KnowledgeRecords { get; init; }
    public int RouteNodes { get; init; }
    public int RouteEdges { get; init; }
    public IReadOnlyList<string> Warnings { get; init; } = Array.Empty<string>();
}

/// <summary>
/// Imports read-only JSON generated by tools such as bdo-data-extractor, plus hand-authored route,
/// grind-zone, item, recipe, node, and skill exports. No client injection or game modification occurs.
/// </summary>
public sealed class LocalCatalogImporter
{
    private readonly AppDatabase _db;

    public LocalCatalogImporter(AppDatabase db) => _db = db;

    public async Task<LocalImportReport> ImportDirectoryAsync(string directory, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(directory) || !Directory.Exists(directory))
            throw new DirectoryNotFoundException($"Data directory not found: {directory}");

        var warnings = new List<string>();
        var records = new List<KnowledgeRecord>();
        var nodes = new List<RouteNode>();
        var edges = new List<RouteEdge>();
        var pendingFiles = new List<PendingImportFile>();
        var discovered = Directory.EnumerateFiles(directory, "*.json", SearchOption.AllDirectories)
            .Where(path => !path.Contains($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}", StringComparison.OrdinalIgnoreCase))
            .Take(1001)
            .ToList();
        if (discovered.Count > 1000) warnings.Add("Only the first 1,000 JSON files were scanned.");
        var files = discovered.Take(1000).ToList();
        var filesImported = 0;
        var filesSkipped = 0;

        foreach (var path in files)
        {
            ct.ThrowIfCancellationRequested();
            try
            {
                var info = new FileInfo(path);
                if (info.Length > 512L * 1024 * 1024)
                {
                    warnings.Add($"Skipped {info.Name}: larger than 512 MB.");
                    continue;
                }

                var fullPath = Path.GetFullPath(path);
                var source = "local-" + KnowledgeText.Slug(Path.GetFileNameWithoutExtension(path)) + "-" +
                             KnowledgeText.Hash(fullPath)[..8].ToLowerInvariant();
                if (_db.IsImportFileCurrent(fullPath, info.Length, info.LastWriteTimeUtc))
                {
                    filesSkipped++;
                    continue;
                }

                await using var stream = File.OpenRead(path);
                using var doc = await JsonDocument.ParseAsync(stream, new JsonDocumentOptions
                {
                    AllowTrailingCommas = true,
                    CommentHandling = JsonCommentHandling.Skip,
                    MaxDepth = 128
                }, ct);

                var kind = InferKind(path);
                var recordBefore = records.Count;
                var nodeBefore = nodes.Count;
                var edgeBefore = edges.Count;
                var ordinal = 0;
                foreach (var obj in EnumerateObjects(doc.RootElement, maxObjects: 200_000))
                {
                    ct.ThrowIfCancellationRequested();
                    ordinal++;
                    if (TryBuildRecord(obj, source, kind, ordinal, path, out var record))
                        records.Add(record);
                    if (TryBuildRouteNode(obj, source, kind, out var node))
                        nodes.Add(node);
                    if (TryBuildRouteEdge(obj, source, out var edge))
                        edges.Add(edge);
                }

                if (records.Count == recordBefore)
                {
                    var raw = KnowledgeText.Truncate(doc.RootElement.GetRawText(), 40_000);
                    records.Add(new KnowledgeRecord
                    {
                        SourceId = source,
                        ExternalId = KnowledgeText.Hash(fullPath)[..24],
                        Kind = kind,
                        Title = Path.GetFileName(path),
                        Summary = "Imported local Black Desert data file.",
                        Content = raw,
                        Region = "global",
                        Tags = $"local import {kind}",
                        MetadataJson = JsonSerializer.Serialize(new { file = fullPath, bytes = info.Length }),
                        RetrievedAt = DateTimeOffset.UtcNow,
                        Confidence = 0.9,
                        ContentHash = KnowledgeText.Hash(raw)
                    });
                }

                filesImported++;
                pendingFiles.Add(new PendingImportFile(
                    fullPath,
                    source,
                    info.Length,
                    info.LastWriteTimeUtc,
                    records.Count - recordBefore,
                    nodes.Count - nodeBefore,
                    edges.Count - edgeBefore));
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or JsonException)
            {
                warnings.Add($"{Path.GetFileName(path)}: {ex.Message}");
            }
        }

        // Keep the newest duplicate from each source/key and avoid bloating a single transaction.
        var uniqueRecords = records.GroupBy(x => (x.SourceId, x.ExternalId)).Select(g => g.Last()).ToList();
        var uniqueNodes = nodes.GroupBy(x => x.Key).Select(g => g.Last()).ToList();
        var uniqueEdges = edges.GroupBy(x => (x.FromKey, x.ToKey, x.Transport)).Select(g => g.Last()).ToList();

        var recordCount = 0;
        foreach (var batch in uniqueRecords.Chunk(2_000))
            recordCount += _db.UpsertKnowledgeBatch(batch);
        var nodeCount = _db.UpsertRouteNodes(uniqueNodes);
        var edgeCount = _db.UpsertRouteEdges(uniqueEdges);
        foreach (var file in pendingFiles)
            _db.MarkImportFile(file.Path, file.SourceId, file.SizeBytes, file.ModifiedUtc, file.RecordCount, file.NodeCount, file.EdgeCount);

        return new LocalImportReport
        {
            FilesScanned = files.Count,
            FilesImported = filesImported,
            FilesSkipped = filesSkipped,
            KnowledgeRecords = recordCount,
            RouteNodes = nodeCount,
            RouteEdges = edgeCount,
            Warnings = warnings
        };
    }

    private static IEnumerable<JsonElement> EnumerateObjects(JsonElement root, int maxObjects)
    {
        var stack = new Stack<JsonElement>();
        stack.Push(root);
        var count = 0;
        while (stack.Count > 0 && count < maxObjects)
        {
            var current = stack.Pop();
            switch (current.ValueKind)
            {
                case JsonValueKind.Object:
                    count++;
                    yield return current;
                    foreach (var prop in current.EnumerateObject())
                        if (prop.Value.ValueKind is JsonValueKind.Array or JsonValueKind.Object)
                            stack.Push(prop.Value);
                    break;
                case JsonValueKind.Array:
                    foreach (var child in current.EnumerateArray())
                        if (child.ValueKind is JsonValueKind.Array or JsonValueKind.Object)
                            stack.Push(child);
                    break;
            }
        }
    }

    private static bool TryBuildRecord(JsonElement obj, string source, string inferredKind, int ordinal, string path, out KnowledgeRecord record)
    {
        record = new KnowledgeRecord();
        var name = String(obj, "name", "title", "itemName", "displayName", "Name");
        var id = String(obj, "id", "key", "itemId", "mainKey", "nodeId", "skillId", "recipeId");
        if (string.IsNullOrWhiteSpace(name) && string.IsNullOrWhiteSpace(id)) return false;
        name = string.IsNullOrWhiteSpace(name) ? $"{inferredKind} {id}" : name;
        id = string.IsNullOrWhiteSpace(id) ? KnowledgeText.Hash(source, name, ordinal.ToString(CultureInfo.InvariantCulture))[..24] : id;

        var raw = KnowledgeText.Truncate(obj.GetRawText(), 20_000);
        var description = String(obj, "description", "desc", "tooltip", "summary", "effect", "contents");
        var kind = String(obj, "kind", "type", "category")?.ToLowerInvariant() switch
        {
            "item" => KnowledgeKinds.Item,
            "recipe" => KnowledgeKinds.Recipe,
            "node" => KnowledgeKinds.Node,
            "skill" => KnowledgeKinds.Skill,
            "grind-zone" or "grindzone" or "monster-zone" => KnowledgeKinds.GrindZone,
            _ => inferredKind
        };
        var tags = string.Join(' ', new[]
        {
            kind,
            String(obj, "category", "subCategory", "territory", "class", "className"),
            String(obj, "tags")
        }.Where(x => !string.IsNullOrWhiteSpace(x)));

        record = new KnowledgeRecord
        {
            SourceId = source,
            ExternalId = id!,
            Kind = kind,
            Title = name!,
            Summary = KnowledgeText.Truncate(description ?? BuildCompactSummary(obj), 800),
            Content = raw,
            Region = String(obj, "region")?.ToLowerInvariant() ?? "global",
            Tags = tags,
            MetadataJson = JsonSerializer.Serialize(new { file = Path.GetFullPath(path) }),
            EffectiveAt = Date(obj, "updatedAt", "effectiveAt", "patchDate"),
            RetrievedAt = DateTimeOffset.UtcNow,
            Confidence = 0.92,
            ContentHash = KnowledgeText.Hash(raw)
        };
        return true;
    }

    private static bool TryBuildRouteNode(JsonElement obj, string source, string kind, out RouteNode node)
    {
        node = new RouteNode();
        var name = String(obj, "name", "title", "zoneName", "nodeName");
        if (string.IsNullOrWhiteSpace(name)) return false;

        var ap = Int(obj, "recommendedAp", "ap", "minAp", "recAp");
        var dp = Int(obj, "recommendedDp", "dp", "minDp", "recDp");
        var silver = Long(obj, "expectedSilverPerHour", "silverPerHour", "silverHour", "profitPerHour", "avgSilverPerHour");
        var x = Double(obj, "x", "posX", "worldX", "longitude");
        var y = Double(obj, "y", "posY", "worldY", "latitude");
        var hasRoutingValue = kind is KnowledgeKinds.GrindZone or KnowledgeKinds.Node || ap > 0 || dp > 0 || silver > 0 || x != 0 || y != 0;
        if (!hasRoutingValue) return false;

        var key = String(obj, "key", "id", "nodeId", "zoneId");
        key = string.IsNullOrWhiteSpace(key) ? KnowledgeText.Slug(name!) : key;
        node = new RouteNode
        {
            Key = key!,
            Name = name!,
            Territory = String(obj, "territory", "region", "area") ?? "",
            X = x,
            Y = y,
            RecommendedAp = ap,
            RecommendedDp = dp,
            ExpectedSilverPerHour = silver,
            Risk = Math.Clamp(Double(obj, "risk", "danger", "riskScore"), 0, 1),
            Tags = String(obj, "tags", "category") ?? kind,
            SourceId = source,
            UpdatedAt = Date(obj, "updatedAt", "effectiveAt") ?? DateTimeOffset.UtcNow
        };
        return true;
    }

    private static bool TryBuildRouteEdge(JsonElement obj, string source, out RouteEdge edge)
    {
        edge = new RouteEdge();
        var from = String(obj, "from", "fromKey", "source", "start");
        var to = String(obj, "to", "toKey", "target", "end", "destination");
        var minutes = Double(obj, "travelMinutes", "minutes", "durationMinutes", "time");
        if (string.IsNullOrWhiteSpace(from) || string.IsNullOrWhiteSpace(to) || minutes <= 0) return false;

        edge = new RouteEdge
        {
            FromKey = from!,
            ToKey = to!,
            TravelMinutes = minutes,
            Risk = Math.Clamp(Double(obj, "risk", "danger"), 0, 1),
            Bidirectional = Bool(obj, true, "bidirectional", "twoWay", "bothWays"),
            Transport = String(obj, "transport", "mode", "type") ?? "ground",
            SourceId = source,
            UpdatedAt = Date(obj, "updatedAt", "effectiveAt") ?? DateTimeOffset.UtcNow
        };
        return true;
    }

    private static string InferKind(string path)
    {
        var name = Path.GetFileNameWithoutExtension(path).ToLowerInvariant();
        if (name.Contains("recipe") || name.Contains("cook") || name.Contains("alchemy")) return KnowledgeKinds.Recipe;
        if (name.Contains("skill")) return KnowledgeKinds.Skill;
        if (name.Contains("grind") || name.Contains("monster-zone") || name.Contains("spot")) return KnowledgeKinds.GrindZone;
        if (name.Contains("node") || name.Contains("route") || name.Contains("map")) return KnowledgeKinds.Node;
        if (name.Contains("item") || name.Contains("equipment")) return KnowledgeKinds.Item;
        return KnowledgeKinds.Other;
    }

    private static string BuildCompactSummary(JsonElement obj)
    {
        var parts = new List<string>();
        foreach (var p in obj.EnumerateObject().Take(12))
        {
            if (p.Value.ValueKind is JsonValueKind.String or JsonValueKind.Number or JsonValueKind.True or JsonValueKind.False)
                parts.Add($"{p.Name}: {KnowledgeText.Truncate(p.Value.ToString(), 160)}");
        }
        return string.Join("; ", parts);
    }

    private static string? String(JsonElement e, params string[] names)
    {
        foreach (var name in names)
            if (TryProperty(e, name, out var p))
                return p.ValueKind switch
                {
                    JsonValueKind.String => p.GetString(),
                    JsonValueKind.Number => p.ToString(),
                    _ => null
                };
        return null;
    }

    private static long Long(JsonElement e, params string[] names)
    {
        foreach (var name in names)
            if (TryProperty(e, name, out var p))
            {
                if (p.ValueKind == JsonValueKind.Number && p.TryGetInt64(out var n)) return n;
                if (long.TryParse(p.ToString().Replace(",", "", StringComparison.Ordinal), NumberStyles.Any, CultureInfo.InvariantCulture, out n)) return n;
            }
        return 0;
    }

    private static int Int(JsonElement e, params string[] names) => (int)Math.Clamp(Long(e, names), int.MinValue, int.MaxValue);

    private static double Double(JsonElement e, params string[] names)
    {
        foreach (var name in names)
            if (TryProperty(e, name, out var p))
            {
                if (p.ValueKind == JsonValueKind.Number && p.TryGetDouble(out var n)) return n;
                if (double.TryParse(p.ToString(), NumberStyles.Any, CultureInfo.InvariantCulture, out n)) return n;
            }
        return 0;
    }

    private static bool Bool(JsonElement e, bool fallback, params string[] names)
    {
        foreach (var name in names)
            if (TryProperty(e, name, out var p))
            {
                if (p.ValueKind is JsonValueKind.True or JsonValueKind.False) return p.GetBoolean();
                if (bool.TryParse(p.ToString(), out var value)) return value;
                if (int.TryParse(p.ToString(), out var i)) return i != 0;
            }
        return fallback;
    }

    private static DateTimeOffset? Date(JsonElement e, params string[] names)
    {
        var s = String(e, names);
        return DateTimeOffset.TryParse(s, out var value) ? value : null;
    }

    private sealed record PendingImportFile(
        string Path,
        string SourceId,
        long SizeBytes,
        DateTime ModifiedUtc,
        int RecordCount,
        int NodeCount,
        int EdgeCount);

    private static bool TryProperty(JsonElement e, string name, out JsonElement value)
    {
        if (e.TryGetProperty(name, out value)) return true;
        foreach (var prop in e.EnumerateObject())
            if (prop.Name.Equals(name, StringComparison.OrdinalIgnoreCase))
            {
                value = prop.Value;
                return true;
            }
        value = default;
        return false;
    }
}
